market_types = ["Mass Market", "Niche Market", "Regional Market", "Global Market", "Enterprise Market"]
company_values= ["Innovation", "Sustainability", "Customer-Centric", "Diversity and Inclusion", "Transparency"]
business_models = ["E-commerce", "Subscription-Based", "Freemium", "Marketplace", "Software as a Service (SaaS)", "Advertising Model", "Direct Sales Model"]

industry_list = [
    "None",
    "Advertising Agencies",
    "Aerospace & Defense",
    "Agricultural Chemicals",
    "Agricultural Inputs",
    "Air Delivery & Freight Services",
    "Airports & Air Services",
    "Airlines",
    "Aluminum",
    "Apparel Manufacturing",
    "Apparel Retail",
    "Application Software",
    "Auto & Truck Dealerships",
    "Auto Manufacturers",
    "Banks—Diversified",
    "Banks—Regional",
    "Beverages—Brewers",
    "Beverages—Non-Alcoholic",
    "Beverages—Wineries & Distilleries",
    "Biotechnology",
    "Broadcasting",
    "Broadcasting - TV",
    "Building Materials",
    "Building Materials Wholesale",
    "Building Products & Equipment",
    "Business Equipment & Supplies",
    "Business Services",
    "CATV Systems",
    "Capital Markets",
    "Chemicals",
    "Clothing & Accessories",
    "Coking Coal",
    "Communication Equipment",
    "Communication Services",
    "Computer Hardware",
    "Conglomerates",
    "Consulting Services",
    "Consumer Electronics",
    "Confectioners",
    "Credit Services",
    "Department Stores",
    "Diagnostics & Research",
    "Discount Stores",
    "Diversified Communication Services",
    "Diversified Electronics",
    "Diversified Machinery",
    "Diversified Utilities",
    "Drug Manufacturers—General",
    "Drug Manufacturers—Specialty & Generic",
    "Education & Training Services",
    "Electronic Components",
    "Electronic Gaming & Multimedia",
    "Electrical Equipment & Parts",
    "Electronics & Computer Distribution",
    "Entertainment",
    "Financial Conglomerates",
    "Financial Data & Stock Exchanges",
    "Food Distribution",
    "Footwear & Accessories",
    "Furnishings, Fixtures & Appliances",
    "Gambling",
    "General Building Materials",
    "General Contractors",
    "Gold",
    "Grocery Stores",
    "Health Care Equipment & Services",
    "Health Information Services",
    "Healthcare Plans",
    "Home Improvement Retail",
    "Homebuilding & Construction",
    "Household & Personal Products",
    "Industrial Distribution",
    "Industrial Metals & Minerals",
    "Infrastructure Operations",
    "Insurance Brokers",
    "Insurance—Diversified",
    "Insurance—Life",
    "Insurance—Property & Casualty",
    "Insurance—Reinsurance",
    "Integrated Freight & Logistics",
    "Internet Content & Information",
    "Internet Retail",
    "Jewelry Stores",
    "Leisure",
    "Lodging",
    "Lumber & Wood Production",
    "Lumber, Wood Production",
    "Luxury Goods",
    "MARINE SHIPPING",
    "Marketing Services",
    "Materials",
    "Medical Care Facilities",
    "Medical Devices",
    "Medical Distribution",
    "Medical Instruments & Supplies",
    "Metal Fabrication",
    "Mortgage Finance",
    "Oil & Gas Drilling",
    "Oil & Gas E&P",
    "Oil & Gas Equipment & Services",
    "Oil & Gas Integrated",
    "Oil & Gas Midstream",
    "Oil & Gas Refining & Marketing",
    "Oil & Gas—Integrated",
    "Other Industrial Metals & Mining",
    "Other Precious Metals & Mining",
    "Packaged Foods",
    "Packaging & Containers",
    "Paper & Paper Products",
    "Personal Services",
    "Pharmaceutical Retailers",
    "Pollution & Treatment Controls",
    "Publishing",
    "Rental & Leasing Services",
    "Recreational Vehicles",
    "Real Estate",
    "Real Estate Development",
    "Real Estate Services",
    "Real Estate—Development",
    "Real Estate—Diversified",
    "Real Estate—Industrial",
    "Real Estate—Residential",
    "Reinsurance",
    "Residential Construction",
    "Resorts & Casinos",
    "Restaurants",
    "Retails",
    "Retails—Apparel & Specialty",
    "Retails—Building Materials",
    "Retails—Electronic Components",
    "Retails—Home Improvement",
    "Retails—Luxury Goods",
    "Retails—Restaurants",
    "Retails—Specialty",
    "Retail Apparel & Specialty",
    "Retail—Apparel & Specialty",
    "Retail—Building Materials",
    "Retail—Electronic Components",
    "Retail—Home Improvement",
    "Retail—Luxury Goods",
    "Retail—Restaurants",
    "Retail—Specialty",
    "Security & Protection Services",
    "Semiconductor Equipment & Materials",
    "Semiconductors",
    "Shell Companies",
    "Shipping",
    "Silver",
    "Software & Services",
    "Software—Application",
    "Software—Infrastructure",
    "Specialty Business Services",
    "Specialty Chemicals",
    "Specialty Industrial Machinery",
    "Specialty Retail",
    "Steel",
    "Steel & Iron",
    "Technical & System Software",
    "Telecom Services",
    "Telecom Services - Foreign",
    "Textile Industrial",
    "Textile Manufacturing",
    "Thermal Coal",
    "Tools & Accessories",
    "Trucking",
    "Uranium",
    "Utilities Diversified",
    "Utilities—Diversified",
    "Utilities—Independent Power Producers",
    "Utilities—Regulated Electric",
    "Utilities—Regulated Gas",
    "Utilities—Regulated Water",
    "Utilities—Renewable",
    "Utilities—Regulated",
    "Utilities—Regulated Electric",
    "Utilities—Regulated Gas",
    "Utilities—Regulated Water",
    "Utilities—Renewable",
    "Waste Management",
]

